src/classifieds/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings
from django.views.generic.edit import CreateView
from main.forms import *
from django.conf.urls import *

admin.autodiscover()

urlpatterns = patterns('',
    url(r'^assets/(?P<path>.*)$','django.views.static.serve',
        {'document_root':settings.MEDIA_ROOT}
    ),
    url(r'^uploads/(?P<path>.*)$','django.views.static.serve',
        {'document_root':settings.MEDIA_ROOT}
    ),

    url(r'^$', 'main.views.index'),

    url(r'^api/json/location/cities', 'main.views.jsonCities'),

    url(r'^ads/find/', 'main.views.listClassifieds'),
    url(r'^ads/category/(?P<categoryName>[a-z]{1,64})/$', 'main.views.listClassifieds'),
    url(r'^ads/(?P<classifiedId>[0-9]{1,8})/contact$', 'main.views.contactSeller'),
    url(r'^ads/(?P<classifiedId>[0-9]{1,8})/(?P<classifiedTitle>[a-zA-Z0-9_\-\/]{0,95})$', 'main.views.viewClassified'),
    url(r'^ads/edit/(?P<classifiedId>[0-9]{1,8})$', 'main.views.editClassified'),
    url(r'^ads/delete/(?P<classifiedId>[0-9]{1,8})$', 'main.views.deleteClassified'),
    url(r'^ads/create/$', 'main.views.addClassified'),

    url(r'^accounts/register/$', 'main.views.registerUser'),
    url(r'^accounts/profile/$', 'main.views.myProfile'),
    url(r'^accounts/profile/classifieds$', 'main.views.myClassifieds'),
    url(r'^accounts/logout/$', 'main.views.logout'),
    #url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
    url(r'^accounts/login/$', 'main.views.login'),
    url(r'^accounts/password/change/$', 'django.contrib.auth.views.password_change', {'template_name': 'registration/password_change_form.html'}),
    url(r'^accounts/password/change/done/$', 'django.contrib.auth.views.password_change_done', {'template_name': 'registration/password_change_done.html'}),

    url(r'^accounts/password/reset/$', 'django.contrib.auth.views.password_reset', {'post_reset_redirect' : '/accounts/password/reset/done/'}),
    url(r'^accounts/password/reset/done/$', 'django.contrib.auth.views.password_reset_done'), 
    url(r'^accounts/password/reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 'django.contrib.auth.views.password_reset_confirm', {'post_reset_redirect' : '/accounts/password/done/'}),
    url(r'^accounts/password/done/$', 'django.contrib.auth.views.password_reset_complete'),

    url(r'^admin/', include(admin.site.urls)),
)

src/main/models/classifieds.py
# -*- coding: utf-8 -*-
import datetime, calendar, re
from django.db import models
from django.contrib.auth.models import User
from main.models.categories import ClassifiedCategory
from main.models.status import ClassifiedStatus
from main.models.locations import City, Province
from main.helpers import Upload

class Classified(models.Model):

    CLASSIFIED_EXPIRATION_MONTHS = 1

    CLASSIFIED_STATUS = (
        (0, 'Inactive'),
        (1, 'Active'),
    )
    CLASSIFIED_TYPES = (
        ('sale', 'For sale'),
        ('rent', 'For rent'),
    )
    CLASSIFIED_CURRENCIES = (
        ('', 'Select currency'),
        ('usd', 'Dollar'),
        ('peso_arg', 'Argentine Peso'),
    )

    def addMonths(sourcedate, months):
        month = sourcedate.month - 1 + months
        year = sourcedate.year + month / 12
        month = month % 12 + 1
        day = min(sourcedate.day,calendar.monthrange(year,month)[1])
        return datetime.date(year,month,day)

    @property
    def permalink(self, max_length = 45):
        title = re.sub('[^0-9a-zA-Z]+', ' ', self.title).strip()
        category = self.category.title.lower()
        return '%d/%s/%s' % (self.id, category, title[:max_length].lower().replace(' ', '-'))

    @property
    def image_1_thumbs(self):
        return Upload.getClasifiedThumbs(getattr(self, 'image_1'))

    @property
    def image_2_thumbs(self):
        return Upload.getClasifiedThumbs(getattr(self, 'image_2'))

    @property
    def image_3_thumbs(self):
        return Upload.getClasifiedThumbs(getattr(self, 'image_3'))

    def is_owner(self, user):
        owner = True
        if not self.user and not self.contact_email and not user:
            owner = False
        elif user != self.user and user.email != self.contact_email:
            owner = False
        return owner

    title = models.CharField(max_length = 255)
    content = models.TextField()
    user = models.ForeignKey(User, null = True, blank = True)
    category = models.ForeignKey(ClassifiedCategory)
    status = models.SmallIntegerField(max_length = 1, choices = CLASSIFIED_STATUS, default = 1)
    type = models.CharField(max_length = 12, choices = CLASSIFIED_TYPES, default = 'sale')
    currency = models.CharField(max_length = 12, choices = CLASSIFIED_CURRENCIES, default = 'peso_arg')
    created = models.DateTimeField(auto_now = True)
    expires = models.DateTimeField(default = addMonths(datetime.date.today(), CLASSIFIED_EXPIRATION_MONTHS))
    price = models.FloatField()
    
    city = models.ForeignKey(City, null = True, blank = True)
    contact_address = models.CharField(max_length = 128, null = True, blank = True)
    
    contact_name =  models.CharField(max_length = 64, null = True)
    contact_email = models.CharField(max_length = 128, null = True)
    contact_phone = models.CharField(max_length = 64, null = True, blank = True)
    google_map = models.CharField(max_length = 128, null = True, blank = True)
    visits = models.IntegerField(default = 0, null = True, blank = True)

    image_1 = models.ImageField(upload_to = Upload.generateRandomFilename('classifieds/images'), blank = True)
    image_2 = models.ImageField(upload_to = Upload.generateRandomFilename('classifieds/images'), blank = True)
    image_3 = models.ImageField(upload_to = Upload.generateRandomFilename('classifieds/images'), blank = True)

    class Meta:
        verbose_name_plural = 'Classifieds'
        app_label = 'main'
        db_table = 'main_classifieds'

    def __unicode__(self):
        return self.title

src/classifieds/templates/classifieds/contact_seller.html
{% extends 'base.html' %}
{% block title %}Contact seller{% endblock %}
{% block header %} 
    <h2>Contact seller</h2>
{% endblock %}

{% block main_content %}
<div class="span9">
    <h3>{{ classified.title }}</h3>
    <form method="post" action="" class='form-horizontal'>
        <fieldset>
            {% csrf_token %}
            <table class='table table-striped table-bordered table-hover '>
                {{ formset }}
            </table>
            <input class="btn btn-primary" type="submit" value="Contact" />
        </fieldset>
    </form>
</div>
{% endblock %}

src/classifieds/templates/classifieds/create.html
{% extends 'base.html' %}
{% block title %}Create classified{% endblock %}
{% block header %} 
    <h2>Create classified</h2>
{% endblock %}

{% block main_content %}

<form method='post' class="create-ad" enctype='multipart/form-data'>
    {% csrf_token %}
    <div class="span8 noleft">
        <div class="well tospan7">

            <div class="span7 {% if formset.title.errors %}wrap-error{% endif %}">
              {{ formset.title }}
              {% if formset.title.errors %}
                <span class="alert alert-error"><i class="icon icon-remove"></i>{{ formset.title.errors|striptags }}</span>
              {% endif %}
            </div>

            <div class="span7 {% if formset.content.errors %}wrap-error{% endif %}">
              {{ formset.content }}
              {% if formset.content.errors %}
                <span class="alert alert-error"><i class="icon icon-remove"></i>{{ formset.content.errors|striptags }}</span>
              {% endif %}
            </div>
            
            <div class="clearfix">
                <div class="span2 {% if formset.image_1.errors %}wrap-error{% endif %}">
                  {{ formset.image_1 }}
                  <!--<button class="btn"><i class="icon-paper-clip"></i>Add image</button>-->
                  {% if formset.image_1.errors %}
                    <span class="alert alert-error"><i class="icon icon-remove"></i>{{ formset.image_1.errors|striptags }}</span>
                  {% endif %}
                </div>

                <div class="span2 {% if formset.image_2.errors %}wrap-error{% endif %}">
                  {{ formset.image_2 }}
                  {% if formset.image_2.errors %}
                    <span class="alert alert-error"><i class="icon icon-remove"></i>{{ formset.image_2.errors|striptags }}</span>
                  {% endif %}
                </div>
                <div class="span2 {% if formset.image_3.errors %}wrap-error{% endif %}">
                  {{ formset.image_3 }}
                  {% if formset.image_3.errors %}
                    <span class="alert alert-error"><i class="icon icon-remove"></i>{{ formset.image_3.errors|striptags }}</span>
                  {% endif %}
                </div>

            </div>

            <hr/>

            <div class="controls controls-row">
              <div class="span3 {% if formset.price.errors %}wrap-error{% endif %}">
                {{ formset.price }}
                {% if formset.price.errors %}
                  <span class="alert alert-error"><i class="icon icon-remove"></i>{{ formset.price.errors|striptags }}</span>
                {% endif %}
              </div>
              <div class="span3 {% if formset.currency.errors %}wrap-error{% endif %}">
                {{ formset.currency }}
                {% if formset.currency.errors %}
                  <span class="alert alert-error"><i class="icon icon-remove"></i>{{ formset.currency.errors|striptags }}</span>
                {% endif %}
              </div>

              <div class="span3 {% if formset.category.errors %}wrap-error{% endif %}">
                {{ formset.category }}
                {% if formset.category.errors %}
                  <span class="alert alert-error"><i class="icon icon-remove"></i>{{ formset.category.errors|striptags }}</span>
                {% endif %}
              </div>
              <div class="span3 {% if formset.type.errors %}wrap-error{% endif %}">
                {{ formset.type }}
                {% if formset.type.errors %}
                  <span class="alert alert-error"><i class="icon icon-remove"></i>{{ formset.type.errors|striptags }}</span>
                {% endif %}
              </div>
            </div>
        </div>
    </div>
    <div class="span4 noleft">
        <div class="well tospan3">
            <h6>Contact info</h6>


            <div class="span3 {% if formset.city.errors %}wrap-error{% endif %}">
              {{ formset.city }}
              {{ formset.city_id }}
              {% if formset.city.errors %}
                <span class="alert alert-error"><i class="icon icon-remove"></i>{{ formset.city.errors|striptags }}</span>
              {% endif %}
            </div>

            <div class="span3 {% if formset.contact_address.errors %}wrap-error{% endif %}">
              {{ formset.contact_address }}
              {% if formset.contact_address.errors %}
                <span class="alert alert-error"><i class="icon icon-remove"></i>{{ formset.contact_address.errors|striptags }}</span>
              {% endif %}
            </div>

            <div class="span3 {% if formset.contact_phone.errors %}wrap-error{% endif %}">
              {{ formset.contact_phone }}
              {% if formset.contact_phone.errors %}
                <span class="alert alert-error"><i class="icon icon-remove"></i>{{ formset.contact_phone.errors|striptags }}</span>
              {% endif %}
            </div>

            <div class="span3 {% if formset.contact_name.errors %}wrap-error{% endif %}">
              {{ formset.contact_name }}
              {% if formset.contact_name.errors %}
                <span class="alert alert-error"><i class="icon icon-remove"></i>{{ formset.contact_name.errors|striptags }}</span>
              {% endif %}
            </div>

            <div class="span3 {% if formset.contact_email.errors %}wrap-error{% endif %}">
              {{ formset.contact_email }}
              {% if formset.contact_email.errors %}
                <span class="alert alert-error"><i class="icon icon-remove"></i>{{ formset.contact_email.errors|striptags }}</span>
              {% endif %}
            </div>

            <div class="span3 {% if formset.google_map.errors %}wrap-error{% endif %}">
              {{ formset.google_map }}
              {% if formset.google_map.errors %}
                <span class="alert alert-error"><i class="icon icon-remove"></i>{{ formset.google_map.errors|striptags }}</span>
              {% endif %}
            </div>

            <button class="btn btn-primary">Publish Classified</button>
            <button class="btn btn-danger">Cancel</button>
        </div>
    </div>
</form>

{% endblock %}

{% block inline_script %}
<script>
$(document).ready(function(){
    $('.controls-row').find('input,select').addClass('span3');
    $('input, textarea').each(function(i, e) {
      $(e).attr('placeholder', $(e).attr('name').preety().ucwords());
    });
    $('.tospan3').find('input, select, textarea').each(function(i, e) {
      $(e).addClass('span3');
    });
    $('.tospan7').find('input, select, textarea').each(function(i, e) {
      $(e).addClass('span7');
    });
});
</script>
{% endblock %}

src/classifieds/templates/classifieds/delete.html
{% extends 'base.html' %}
{% block title %}Delete Classified{% endblock %}
{% block header %} 
    <h2>Delete Classified</h2>
{% endblock %}

{% block main_content %}
<div class="span9">
    <h3>Do you want to delete: "{{ classified.title }}"?</h3>
    <form id='delete-ad' method='post' class='form-horizontal' enctype='multipart/form-data'>
        <fieldset>
            {% csrf_token %}
            <p>
                <input type='button' class='btn' value='Cancel' />
                <input type='submit' class='btn btn-danger' value='Yes, delete it !' />
            </p>
        </fieldset>
    </form>
</div>
{% endblock %}

src/classifieds/templates/classifieds/list.html
{% extends 'base.html' %}
{% block title %}Classifieds list{% endblock %}
{% block header %} 
    <h2>Listing</h2>
    <p class="big grey">
      {% if request.GET.search %}
        Looking up classifieds for "{{ request.GET.search }}"
      {% else %}
        Look up classifieds
      {% endif %}
    </p>
{% endblock %}
{% block main_content %}
<div class="span3">
  {% include 'misc/layouts/left_side_bar.html' %}
</div>
<div class="span9">
  <div class="row-fluid">
    <ul class="thumbnails">
      <div class="span12">
        {% for classified in classifieds %}
          {% include 'classifieds/list_item.html' %}
        {% endfor %}
      </div>
    </ul>
    {% include 'misc/classifieds/pagination.html' %}
  </div>
</div>
{% endblock %}

src/classifieds/templates/classifieds/list_item.html
<div class="time">
  <div class="tidate b-blue">
     <a href="/ads/{{ classified.permalink }}">{{ classified.title }}</a>
  </div>
  <div class="timatter clearfix">
    {% if classified.image_1 %}
    <div class="thumbnail span3">
      <a href="/ads/{{ classified.permalink }}">
        <img src="/uploads/{{ classified.image_1_thumbs.thumb150x110 }}" alt="{{ classified.title }}" />
      </a>
    </div>
    {% endif %}
    <div class="span{% if classified.image_1 %}9{% endif %}">
      <p>{{ classified.content|slice:":220"  }}...</p>
      <hr />
      <div class="row-fluid">
        <div class="span4">
          <span><i class="icon icon-map-marker"></i>{{ classified.city }}, {{ classified.city.province }}</span>
        </div>
        <div class="span2">
          <span><i class="icon icon-shopping-cart"></i><b>${{ classified.price }}</b></span>
        </div>
        <div class="span3">
          <span><i class="icon icon-eye-open"></i><b>{{ classified.visits }}</b> Visits</span>
        </div>
        <div class="span3">
          <span><i class="icon icon-calendar"></i>{{ classified.created|date:"d/m/Y" }}</span>
        </div>
      </div>
    </div>
  </div>
</div>

src/classifieds/templates/classifieds/myclassifieds.html
{% extends 'base.html' %}
{% block title %}My classifieds list{% endblock %}
{% block header %} 
    <h2>My classifieds list</h2>
{% endblock %}


{% block main_content %}
<div class="span9">
  <ul class="thumbnails">
  {% for classified in classifieds %}
    <li class="span3">
      <div class="thumbnail" style="padding: 0">
        <a href='/ads/{{ classified.permalink }}'>
          <img src="/uploads/{{ classified.image_1 }}" alt="{{ classified.title }}" />
        </a>
        <div class="caption">
          <h4><a href='/ads/{{ classified.permalink }}'>{{ classified.title }}sa</a></h4>
          <p>{{ classified.content|slice:":200"  }}...</p>
          <p><i class="icon icon-map-marker"></i> {{ classified.city }}, {{ classified.city.province }}</p>
        </div>
        <div class="modal-footer" style="text-align: center; padding:8px">  
          <span><b>${{ classified.price }}</b> {{ classified.get_currency_display }}</span>
          <span> - <b>223{{ classified.visits }}</b> Visits</span>
        </div>
      </div>
    </li>
  {% endfor %}
  </ul>
  {% include 'misc/classifieds/pagination.html' %}
</div>
{% endblock %}

src/classifieds/templates/classifieds/single.html
{% extends 'base.html' %}
{% block title %}Signup{% endblock %}
{% block header %} 
	<h1>Classifieds list</h1>
{% endblock %}


{% block main_content %}
	<div class="row-fluid marketing">
		{% for classified in classifieds %}
	        <div class="span6">
	          <h4>{{ classified.title }}</h4>
	          <p>{{ classified.content }}</p>
	        </div>
		{% endfor %}
	</div>
{% endblock %}

src/classifieds/templates/classifieds/view.html
{% extends 'base.html' %}
{% block title %}{{ classified }}{% endblock %}
{% block header %} 
    <h2>{{ classified }}</h2>
{% endblock %}

{% block main_content %}
<div class="span8">  
    <div id="myCarousel" class="carousel slide">
      <!-- Carousel items -->
      <div class="carousel-inner">
        {% if classified.image_1 %}<div class="active item"><img src="{{MEDIA_URL}}{{ classified.image_1_thumbs.thumb620x410 }}" alt="" /></div>{% endif %}
        {% if classified.image_2 %}<div class="item"><img src="{{MEDIA_URL}}{{ classified.image_2_thumbs.thumb620x410 }}" alt="" /></div>{% endif %}
        {% if classified.image_3 %}<div class="item"><img src="{{MEDIA_URL}}{{ classified.image_3_thumbs.thumb620x410 }}" alt="" /></div>{% endif %}
      </div>
      <!-- Carousel nav -->
      <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
      <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div>
 </div>                        
 <div class="span4"> 
    <div class="prdetails well">
       <h5 class="title">Contact Info</h5>
       <hr />
       <ul>
          <li><strong>Location: </strong>{{ classified.city }}</li>
          <li><strong>Phone: </strong>{{ classified.contact_phone }}</li>
          <li><strong>Email: </strong>{{ classified.contact_email }}</li>
          <li><strong>Name: </strong>{{ classified.contact_name }}</li>
          <li><strong>User: </strong>{{ classified.user }}</li>
          <li><strong>Map: </strong>{{ classified.google_map }}</li>
          <li><strong>Visits: </strong>{{ classified.visits }}</li>
       </ul>
       <hr />
       <!-- Buttons -->
        <a href="/ads/{{ classified.id }}/contact" class="btn btn-info">Contact seller</a>
        <a href="/ads/edit/{{ classified.id }}" class="btn btn-primary">Edit</a>
        <a href="/ads/delete/{{ classified.id }}" class="btn btn-danger">Delete</a>
    </div>
 </div>

 <div class="span12">
  <div class="bor"></div>
  <div class="well">
    <p>{{ classified.content }}</p>
  </div>
    <div class=" well related-projects">
      <!-- Title -->
      <h5 class="title">Details</h5>
       <hr />
       <ul>
          <li><strong>Category: </strong>{{ classified.category }}</li>
          <li><strong>Status: </strong>{{ classified.status }}</li>
          <li><strong>Currency: </strong>{{ classified.currency }}</li>
          <li><strong>Price: </strong>{{ classified.price }}</li>
          <li><strong>Created: </strong>{{ classified.created }}</li>
          <li><strong>Expires: </strong>{{ classified.expires }}</li>
       </ul>
       <hr />
       <h5 class="title">Related items</h5>              
      {% for classified in latestClassifieds %}
        <a href="/ads/{{ classified.permalink }}"><img src="/uploads/{{ classified.image_1_thumbs.thumb150x110 }}" alt="" /></a>
      {% endfor %}
    </div>
  <div class="bor"></div>
 </div>

 


{% endblock %}